"""init db

Revision ID: 73cfe066135e
Revises: 
Create Date: 2025-09-08 02:41:52.654314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cfe066135e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.drop_constraint('entrenamientos_ejercicio_id_fkey', 'entrenamientos', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ejercicios')
    op.drop_table('usuarios')
    op.drop_table('entrenamientos')
    op.drop_table('grupos_musculares')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos_musculares',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('grupos_musculares_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='grupos_musculares_pkey'),
    sa.UniqueConstraint('nombre', name='grupos_musculares_nombre_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('entrenamientos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grupo_muscular_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ejercicio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('repeticiones', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], name=op.f('entrenamientos_ejercicio_id_fkey')),
    sa.ForeignKeyConstraint(['grupo_muscular_id'], ['grupos_musculares.id'], name=op.f('entrenamientos_grupo_muscular_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('entrenamientos_pkey'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genero', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey')),
    sa.UniqueConstraint('email', name=op.f('usuarios_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ejercicios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('musculo_principal', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ejercicios_pkey')),
    sa.UniqueConstraint('nombre', name=op.f('ejercicios_nombre_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
